$filePath = "H:\git\repositorio de Git hub\github-paso-a-paso\11-git-deshacer-y-recuperar\README.md"
$lines = Get-Content -Path $filePath
$insertAt = 9
$conceptualMapLines = @()
$conceptualMapLines += ""
$conceptualMapLines += "## Mapa conceptual de este capítulo"
$conceptualMapLines += "```mermaid"
$conceptualMapLines += "mindmap"
$conceptualMapLines += "  root((11 - Git: deshacer y recuperar))"
$conceptualMapLines += "    Restaurar y descartar cambios"
$conceptualMapLines += "      Working directory"
$conceptualMapLines += "      Index"
$conceptualMapLines += "      git restore"
$conceptualMapLines += "    Deshacer commits compartidos"
$conceptualMapLines += "      git revert"
$conceptualMapLines += "      Shared history"
$conceptualMapLines += "    Mover rama y reset"
$conceptualMapLines += "      git reset"
$conceptualMapLines += "      Reflog"
$conceptualMapLines += "      Reset limits"
$conceptualMapLines += "    Tres modos de reset"
$conceptualMapLines += "      --soft"
$conceptualMapLines += "      --mixed"
$conceptualMapLines += "      --hard"
$conceptualMapLines += "      When to use each"
$conceptualMapLines += "    Git stash"
$conceptualMapLines += "      Stack"
$conceptualMapLines += "      Apply/pop"
$conceptualMapLines += "      Options"
$conceptualMapLines += "      Rescue"
$conceptualMapLines += "```"
$top = $lines[0..($insertAt-2)]
$bottom = $lines[($insertAt-1)..$lines.Length-1]
$newContent = $top + $conceptualMapLines + $bottom
Set-Content -Path $filePath -Value $newContent -Encoding UTF8
